all: treeValidator treeGen richTreeValidator richTreeGen flowValidator flowGen slothValidator slothGen loraxValidator

treeValidator: treeValidator.cpp
	g++ -o treeValidator treeValidator.cpp

treeGen: treeGen.cpp
	g++ -o treeGen treeGen.cpp

richTreeValidator: richTreeValidator.cpp
	g++ -o richTreeValidator richTreeValidator.cpp

richTreeGen: richTreeGen.cpp
	g++ -o richTreeGen richTreeGen.cpp

flowValidator: flowValidator.cpp
	g++ -o flowValidator flowValidator.cpp

flowGen: flowGen.cpp
	g++ -o flowGen flowGen.cpp

slothValidator: slothValidator.cpp
	g++ -o slothValidator slothValidator.cpp

slothGen: slothGen.cpp
	g++ -o slothGen slothGen.cpp

loraxValidator: loraxValidator.cpp
	g++ -o loraxValidator loraxValidator.cpp

